//Mail

var nodemailer = require('nodemailer');

var transport = nodemailer.createTransport({
  host: "smtp.gmail.com",
  port: 587,
  auth: {
    user: "swatimehta744@gmail.com", // generated ethereal user
    pass: "csvx pvmr kjfl zfbp"  //example of generated by Mailtrap 
  }
});

const sendMail = async(toMail,subject,text)=>{
    var mailOptions = {
        from: 'from@example.com',
        to: `${toMail}`,
        subject: subject,
        text:text
      };
    return transport.sendMail(mailOptions)
}

module.exports = {sendMail}